version: "2"
services:
  mysql:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=nms
    networks: 
      - nms
  mongo:
    image: mongo:latest
    expose:
      - "27017"
    networks: 
      - nms
  activemq:
    image: rmohr/activemq
    restart: always
    expose:
      - "5672"
    ports:
      - "5672:5672"
    networks: 
      - nms
  account-microservice:
    image: account-microservice
    links:
      - mongo
    depends_on:
      - mongo
    expose:
      - "8083"
    networks: 
      - nms
  telemetry-microservice:
    image: telemetry-microservice
    links:
      - mongo
      - activemq
    depends_on:
      - mongo
      - activemq
    expose:
      - "8082"
    networks: 
      - nms
  notification-microservice:
    image: notification-microservice
    links:
      - mongo
    depends_on:
      - mongo
    expose:
      - "8086"
    networks: 
      - nms
  topology-microservice:
    image: topology-microservice
    links:
      - mysql
      - notification-microservice
    depends_on:
      - mysql
      - notification-microservice
    expose:
      - "8085"
    networks: 
      - nms
  crossconnect-microservice:
    image: crossconnect-microservice
    links:
      - mysql
      - topology-microservice
      - notification-microservice
    depends_on:
      - mysql
      - topology-microservice
      - notification-microservice
    expose:
      - "8089"
    networks: 
      - nms
  configuration-microservice:
    image: configuration-microservice
    links:
      - mongo
      - topology-microservice
    depends_on:
      - mongo
      - topology-microservice
    expose:
      - "8088"
    networks: 
      - nms
  api-gateway:
    image: api-gateway
    hostname: mnms.controller
    ports:
      - "8787:8787"
    environment:
      - JAVA_OPTS="-Xms128m -Xmx256m"
    extra_hosts:
      - "dockernet:${EXTERNAL_IP}"
    networks: 
      - nms
    volumes:
      - "${CONTROLLER_VOL}:/opt/data"
networks:
  nms:
    driver: bridge